export const RANDOMNUMBER_GENERATOR_ABI = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_vrfCoordinator",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acceptOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "callbackGasLimit",
    inputs: [],
    outputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fee",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getLotteryWinningNumber",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "koanPlayLottery",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "latestLotteryId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "latestRequestId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "numWords",
    inputs: [],
    outputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "randomResult",
    inputs: [],
    outputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rawFulfillRandomWords",
    inputs: [
      { name: "requestId", type: "uint256", internalType: "uint256" },
      {
        name: "randomWords",
        type: "uint256[]",
        internalType: "uint256[]",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requestConfirmations",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sKeyHash",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sSubscriptionId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "s_vrfCoordinator",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IVRFCoordinatorV2Plus",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setCallbackGasLimit",
    inputs: [
      {
        name: "_callbackGasLimit",
        type: "uint32",
        internalType: "uint32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCoordinator",
    inputs: [
      {
        name: "_vrfCoordinator",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setKeyHash",
    inputs: [{ name: "_keyHash", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setLatestLotteryId",
    inputs: [
      {
        name: "_latestLotteryId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setLotteryAddress",
    inputs: [
      {
        name: "_koanPlayLottery",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSubscriptionId",
    inputs: [
      {
        name: "_subscriptionId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "to", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "viewLatestLotteryId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "viewRandomResult",
    inputs: [],
    outputs: [{ name: "", type: "uint32", internalType: "uint32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdrawTokens",
    inputs: [
      {
        name: "_tokenAddress",
        type: "address",
        internalType: "address",
      },
      { name: "_tokenAmount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "CoordinatorSet",
    inputs: [
      {
        name: "vrfCoordinator",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferRequested",
    inputs: [
      {
        name: "from",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "to",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "from",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "to",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "OnlyCoordinatorCanFulfill",
    inputs: [
      { name: "have", type: "address", internalType: "address" },
      { name: "want", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "OnlyOwnerOrCoordinator",
    inputs: [
      { name: "have", type: "address", internalType: "address" },
      { name: "owner", type: "address", internalType: "address" },
      { name: "coordinator", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ZeroAddress", inputs: [] },
] as const;

export const LOTTERY_ABI = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_paymentTokenAddress",
        type: "address",
        internalType: "address",
      },
      {
        name: "_randomNumberGeneratorAddress",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "MAX_LENGTH_LOTTERY",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_TREASURY_FEE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MIN_DISCOUNT_DIVISOR",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MIN_LENGTH_LOTTERY",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "buyTickets",
    inputs: [
      { name: "_lotteryId", type: "uint256", internalType: "uint256" },
      {
        name: "_ticketNumbers",
        type: "uint32[]",
        internalType: "uint32[]",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "calculateTotalPriceForBulkTickets",
    inputs: [
      {
        name: "_discountDivisor",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_priceTicket",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_numberTickets",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "changeRandomGenerator",
    inputs: [
      {
        name: "_randomGeneratorAddress",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimTickets",
    inputs: [
      { name: "_lotteryId", type: "uint256", internalType: "uint256" },
      {
        name: "_ticketIds",
        type: "uint256[]",
        internalType: "uint256[]",
      },
      { name: "_brackets", type: "uint32[]", internalType: "uint32[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "closeLottery",
    inputs: [{ name: "_lotteryId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "currentLotteryId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "currentTicketId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "drawFinalNumberAndMakeLotteryClaimable",
    inputs: [
      { name: "_lotteryId", type: "uint256", internalType: "uint256" },
      { name: "_autoInjection", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "injectFunds",
    inputs: [
      { name: "_lotteryId", type: "uint256", internalType: "uint256" },
      { name: "_amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "injectorAddress",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxNumberTicketsPerBuyOrClaim",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxPriceTicketInPaymentToken",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minPriceTicketInPaymentToken",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "operatorAddress",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paymentToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "paymentTokenDecimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingInjectionNextLottery",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "randomNumberGenerator",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IRandomNumberGenerator",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "recoverWrongTokens",
    inputs: [
      {
        name: "_tokenAddress",
        type: "address",
        internalType: "address",
      },
      { name: "_tokenAmount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMaxNumberTicketsPerBuy",
    inputs: [
      {
        name: "_maxNumberTicketsPerBuy",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMinAndMaxTicketPriceInPaymentToken",
    inputs: [
      {
        name: "_minPriceTicketInPaymentToken",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_maxPriceTicketInPaymentToken",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setOperatorAndTreasuryAndInjectorAddresses",
    inputs: [
      {
        name: "_operatorAddress",
        type: "address",
        internalType: "address",
      },
      {
        name: "_treasuryAddress",
        type: "address",
        internalType: "address",
      },
      {
        name: "_injectorAddress",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "startLottery",
    inputs: [
      { name: "_endTime", type: "uint256", internalType: "uint256" },
      {
        name: "_priceTicketInPaymentToken",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_discountDivisor",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_rewardsBreakdown",
        type: "uint256[6]",
        internalType: "uint256[6]",
      },
      { name: "_treasuryFee", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "treasuryAddress",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "viewCurrentLotteryId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "viewLottery",
    inputs: [{ name: "_lotteryId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct KoanPlayLottery.Lottery",
        components: [
          {
            name: "status",
            type: "uint8",
            internalType: "enum KoanPlayLottery.Status",
          },
          {
            name: "startTime",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "endTime", type: "uint256", internalType: "uint256" },
          {
            name: "priceTicketInPaymentToken",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "discountDivisor",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "rewardsBreakdown",
            type: "uint256[6]",
            internalType: "uint256[6]",
          },
          {
            name: "treasuryFee",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "rewardsPerBracket",
            type: "uint256[6]",
            internalType: "uint256[6]",
          },
          {
            name: "countWinnersPerBracket",
            type: "uint256[6]",
            internalType: "uint256[6]",
          },
          {
            name: "firstTicketId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "firstTicketIdNextLottery",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "amountCollectedInPaymentToken",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "finalNumber",
            type: "uint32",
            internalType: "uint32",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "viewNumbersAndStatusesForTicketIds",
    inputs: [
      {
        name: "_ticketIds",
        type: "uint256[]",
        internalType: "uint256[]",
      },
    ],
    outputs: [
      { name: "", type: "uint32[]", internalType: "uint32[]" },
      { name: "", type: "bool[]", internalType: "bool[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "viewRewardsForTicketId",
    inputs: [
      { name: "_lotteryId", type: "uint256", internalType: "uint256" },
      { name: "_ticketId", type: "uint256", internalType: "uint256" },
      { name: "_bracket", type: "uint32", internalType: "uint32" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "viewUserInfoForLotteryId",
    inputs: [
      { name: "_user", type: "address", internalType: "address" },
      { name: "_lotteryId", type: "uint256", internalType: "uint256" },
      { name: "_cursor", type: "uint256", internalType: "uint256" },
      { name: "_size", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "", type: "uint256[]", internalType: "uint256[]" },
      { name: "", type: "uint32[]", internalType: "uint32[]" },
      { name: "", type: "bool[]", internalType: "bool[]" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AdminTokenRecovery",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LotteryClose",
    inputs: [
      {
        name: "lotteryId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "firstTicketIdNextLottery",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LotteryInjection",
    inputs: [
      {
        name: "lotteryId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "injectedAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LotteryNumberDrawn",
    inputs: [
      {
        name: "lotteryId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "finalNumber",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "countWinningTickets",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LotteryOpen",
    inputs: [
      {
        name: "lotteryId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "startTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "endTime",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "priceTicketInPaymentToken",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "firstTicketId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "injectedAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "NewOperatorAndTreasuryAndInjectorAddresses",
    inputs: [
      {
        name: "operator",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "treasury",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "injector",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "NewRandomGenerator",
    inputs: [
      {
        name: "randomGenerator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TicketsClaim",
    inputs: [
      {
        name: "claimer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "lotteryId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "numberTickets",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TicketsPurchase",
    inputs: [
      {
        name: "buyer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "lotteryId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "numberTickets",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
] as const;
